### ISSUE TITLE
Adding Contributors in README file and adding LICENSE file

### ISSUE THREAD

**Issue by PeritusDeveloper** [Priyanshu85/Digital-Agency#10]
### Proposed Changes

- Acknowledge the Contributing by mentioning them in README along with their profile pictures.
- The list automatically gets updated when there PR is merged.
- Adding LICENSE.md to claim the hard work done in the project as owner's
- Adding Copyright Logo at end of README file

**Comment by PeritusDeveloper** [comment]
I would like to do this

**Comment by Priyanshu85** [comment]
Okay @PeritusDeveloper
