### ISSUE TITLE
Items / paragraphs and buttons re-alignment

### ISSUE THREAD

**Issue by yjwhy** [Priyanshu85/Digital-Agency#12]
Could I work on this particular section to re-align some items? : >
![image](https://user-images.githubusercontent.com/86042155/194692769-618a33f0-eb78-4a78-9071-24ece68a0fa2.png)

**Comment by Priyanshu85** [comment]
Okay...make sure you did not disturb any other section!! @DEV-YJY

**Comment by yjwhy** [comment]
Created PR #13 for this.
Have a look and let me know what you think!

**Comment by Priyanshu85** [comment]
Merged Bruh!! @DEV-YJY
