### ISSUE TITLE
Improve Card Section

### ISSUE THREAD

**Issue by Mahich123** [Priyanshu85/Digital-Agency#4]
I would like to improve these cards as these are overflowing and showing big  can you assign me ?  

![image](https://user-images.githubusercontent.com/69717681/194565020-2fdd4774-2785-4e05-bf7c-3f35e44c35a6.png)
![image](https://user-images.githubusercontent.com/69717681/194565077-07afe326-b756-44af-a9dc-c577d1f11222.png)

**Comment by Priyanshu85** [comment]
I thinks this Looks good...but if you can work upon it to make more better then its On you!!

happy Hacking!!

**Comment by Mahich123** [comment]
Ok . I will show you the update . If you like then merge 😀

**Comment by Mahich123** [comment]
@Priyanshu85  made pr improvements are : 
Before : 
![image](https://user-images.githubusercontent.com/69717681/194601257-729a58d0-b3f6-419d-ae51-e32ea82f1c81.png)
After :
![image](https://user-images.githubusercontent.com/69717681/194601367-5a4c0367-7200-43ce-8580-11cfba283e53.png)
Before:
![image](https://user-images.githubusercontent.com/69717681/194601446-57433ed4-aad5-416d-b352-6d5aed019752.png)
After: 
![image](https://user-images.githubusercontent.com/69717681/194601493-84c1ec09-d13c-48e7-bffa-b5972f3d6d6d.png)

**Comment by Priyanshu85** [comment]
the first cards doesn't looks good @Mahich123

**Comment by Priyanshu85** [comment]
Make it more better @Mahich123
