### ISSUE TITLE
Navbar Improvement

### ISSUE THREAD

**Issue by Abhijeet03s** [Priyanshu85/Digital-Agency#8]
Remove these underlined and give some horizontal margin to make Navbar looks good.

![ezgif com-gif-maker](https://user-images.githubusercontent.com/107188710/194605728-86820e09-0348-4f6c-9ed7-3a2f3a4ffcde.gif)

**Comment by tokyo3001** [comment]
@Abhijeet03s Can you assign me this issue under hacktoberfest2022?

**Comment by karnikagupta30** [comment]
Can you assign me this issue?

**Comment by Priyanshu85** [comment]
Okay @tokyo3001 !!

**Comment by Priyanshu85** [comment]
I will merge the one which one looks goood!! @tokyo3001 @Abhijeet03s

**Comment by Abhijeet03s** [comment]
Hey, @Priyanshu85 I have made some changes. 
1. Change the mobile no icon
2. Fixed navbar padding
3. Removed the underline from Navbar elements and added the hover effect.
4. Added custom scrollbar (if you think the color is not appropriate please tell me I can change that)
5. In the footer section, there is a bug when we hover on Social-icons it changes to text-dark. I change the hover effect.

Check the gif:
![Changes](https://user-images.githubusercontent.com/107188710/195010062-045f0598-7238-4d45-8c80-dbae7eea18d6.gif)

If you think these changes don't look good please let me know.
