### ISSUE TITLE
Add Contributing.md file

### ISSUE THREAD

**Issue by Mitternachtsmond** [Priyanshu85/Digital-Agency#9]
### Proposed Changes

- Add Contributing.md file with all instructions for contributors
- Instructions from forking the project to making a PR will be present
- Additional Links to git tutorial would be present
- Code for each of the above part would be present in case contributors want to avoid the hassle of reading the documentation of git.

**Comment by Priyanshu85** [comment]
someone is already doing it @Mitternachtsmond !!

**Comment by Mitternachtsmond** [comment]
There are neither any issues nor any PR regarding this
Anyways it's fine

**Comment by Priyanshu85** [comment]
Ohh Soryy...that was adding Contributors..coool...You can do thisss!! @Mitternachtsmond
